name: Example Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Ensure id-token: write permission is granted
      contents: read   # This is often needed for accessing repository contents

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print GitHub Token
      run: echo ${{ secrets.GITHUB_TOKEN }}
